### ISSUE TITLE
Use Opus as the main codec

### ISSUE THREAD

**Issue by wolftune** [andrewrk/groovebasin#430] opened 2015-04-10 21:00 UTC
Opus is the best audio codec there is, better than Vorbis (and better than MP3 or others) by basically every measure. Seems ideal to favor Opus as the default for every place and certainly to support playing Opus files.

**Comment by andrewrk** [comment] 2015-04-12 00:11
Opus playback works if your system's libav/ffmpeg library was compiled with it, which is the default in most package managers.

I agree that opus might be an even better candidate than vorbis for the default streaming codec.

duplicate of #144

**Closed by andrewrk** 2015-04-12 00:11 UTC
