### ISSUE TITLE
Demo broken

### ISSUE THREAD

**Issue by knownasilya** [andrewrk/groovebasin#408] opened 2015-01-21 14:49 UTC
Seems like a websocket connection issue

**Comment by andrewrk** [comment] 2015-01-21 16:06
it looks like it's working fine to me. what web browser and version are you using?

**Comment by knownasilya** [comment] 2015-01-21 16:11
Using Chrome Version 39.0.2171.99 (64-bit) on OSX 10.10.1 (14B25).

Error is seen in the dev console:

```
WebSocket connection to 'ws://demo.groovebasin.com/' failed: Error during WebSocket handshake: Unexpected response code: 200 app.js:5359
```

**Comment by andrewrk** [comment] 2015-01-21 16:28
I just tested Chrome Version 39.0.2171.99 (64-bit) on OSX 10.9.5 and it worked fine. I wonder what the deal is.

**Comment by knownasilya** [comment] 2015-01-21 16:31
Same issue with firefox and safari.

**Comment by jvtrigueros** [comment] 2015-01-21 16:45
@knownasilya are you behind a proxy? If the proxy server doesn't support websockets then that might be the reason why it's not working for you. I've had this problem in the past.

**Comment by knownasilya** [comment] 2015-01-21 16:49
Behind a company firewall, not sure about a proxy.

**Comment by jvtrigueros** [comment] 2015-01-21 16:50
Give it a shot when you get home :)

**Comment by andrewrk** [comment] 2015-01-21 16:52
Are you running GrooveBasin over HTTPS? If not, try that.

**Comment by knownasilya** [comment] 2015-01-21 16:55
@andrewrk haven't installed it, only trying the demo from the website.

**Comment by andrewrk** [comment] 2015-01-21 18:14
I bet it would work if I got an SSL cert for the demo and switched to HTTPS.

Going to close this issue, it's your company's firewall that is messing up web sockets, not a bug in groovebasin.

**Closed by andrewrk** 2015-01-21 18:14 UTC

**Comment by norpol** [comment] 2015-01-21 21:10
A friend of mine talks a lot about the gratis ssl option of cloudflare: https://www.cloudflare.com/ssl
Maybe that would be an option for you. (Though, I'm not sure how much traffic you're having - so it might not be gratis for you).
