### ISSUE TITLE
200% CPU on loudness scan (single track) on MinnowBoard Max

### ISSUE THREAD

**Issue by grmpz** [andrewrk/groovebasin#444] opened 2015-06-17 20:15 UTC
Thanks for the work so far!  I'm hoping to get ramped up to the code and contribute soon.  

On MinnowBoard Max (B2) running 64 bit Ubuntu server 15.04 the loudness scan is redlining both cores - CPU 200% for ~5min for a single 54 min mp3.  I'm not sure if this is a symptom of running on a Atom and expected or unexpected.

Log:

loudness scan file complete: Searching for Rick Rubin: The Official Mixtape gain -6.281744787029565 duration 3292.055510199654
[resample @ 0x7f4be00dbec0] First timestamp is missing, assuming 0.
fingerprint scan file complete: Searching for Rick Rubin: The Official Mixtape

While idle (track paused, no scanning noticed) nodejs is running at about 120%.  Unpausing ~ 150% so this could account for the long loudness scan duration, performance.

If this is expected consumption for atom chips go ahead and close.

**Comment by andrewrk** [comment] 2015-06-17 21:01
If it's pegging more than one core, then it's likely scanning more than one album simultaneously.

Are you running the latest release? There was a high CPU usage bug fixed in 1.5.1.

**Comment by grmpz** [comment] 2015-06-17 21:16
I installed it using the ubuntu ppa:andrewrk/libgroove which from what I gather reading other issue threads my be an older version.   The initial import scan has finished.  Before selecting the track the server was >95% idle and once selected (first time track played) it pegged the CPU for roughly 5 minutes.  Once the scan finished the volume normalized (about 5 min in).

I can build from source and retry with a another single mp3 set ~60min unless there's another way to move to 1.5.1.

**Comment by andrewrk** [comment] 2015-06-17 21:18
Yeah, the ppa version is an entire minor version behind, and does not include the CPU bug fix. At this point I suggest running from master branch (or 1.5.1 release tag) of groovebasin.

**Comment by andrewrk** [comment] 2015-06-17 21:29
By the way, that's great that you want to get ramped up on the code and contribute. If you have any questions, the `#libgroove` channel on freenode is a good place to ask them. If I don't answer right away, stick around, I'll see them eventually.

**Comment by andrewrk** [comment] 2015-06-20 22:22
This issue is from an older version and has been fixed. Reopen if you discover the issue is still relevant to master branch.

**Closed by andrewrk** 2015-06-20 22:22 UTC
